version: "3.8"
services:
   db:
      image: mongo
      restart: always
   server:
      image: "node:14.7.0-alpine3.10"
      user: "node"
      working_dir: /home/node/app
      environment:
         - NODE_ENV=production
      volumes:
         - ./server/:/home/node/app
      expose:
         - 5000
      ports:
         - 5000:5000
      depends_on:
        - db
      entrypoint:
         "sh /home/node/app/entrypoint.sh"
   client:
    image: "node:14.7.0-alpine3.10"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./client/:/home/node/app
    ports:
      - 3001:5000
    depends_on:
     - server
    entrypoint:
      "sh /home/node/app/entrypoint.sh"
